### ISSUE TITLE
Small quirk with copy email on mobile

### ISSUE THREAD

**Issue by alexparker** [mariordev/mailtoui#1]
Browser: Chrome
Device: iPhone 7
os: iOS

Details:
Went to demo link, clicked copy email option and the result was the image below. 
I do know that click to copy on mobile can get tricky, but just thought I'd report it so you can track it.

![image](https://user-images.githubusercontent.com/732760/50566270-d6fd7880-0cf4-11e9-8a02-0cd53cdad43f.png)

**Comment by mariordev** [comment]
This issue is now fixed in v0.1.12. Please give it a try and let me know if you have any other issues. Thank you!
