### ISSUE TITLE
how to use this through npm ?

### ISSUE THREAD

**Issue by roeniss** [mariordev/mailtoui#18]
Hi.

i think main docs doesn't provide adequate amount of guide of how to use mailtoui with npm.

Can you explain a little bit more?

```js
// after `npm i mailtoui@1.0.3` :
import mailtoui from "mailtoui"
const mailtoui = require("mailtoui")
```

Both doens't work. Just `Module not found` same error was invoked.

Best, 
Roeniss

**Comment by mariordev** [comment]
Hi, thanks for reaching out. After installing MailtoUI via npm, you only need to require it in your code, like so: 

`const MailtoUI = require('path/to/your/node_modules/mailtoui/dist/mailtoui-min.js')`

This will make the `run` method available, so you can invoke it where appropriate in your code, like so:

`MailtoUI.run()`

The run method can optionally accept an object with any of the options supported (https://mailtoui.com/#options), like so:

`MailtoUI.run({ "autoClose": false })`

Hope this helps!
