### ISSUE TITLE
Trigger manually

### ISSUE THREAD

**Issue by SteveEdson** [mariordev/mailtoui#2]
I'd be great if there was a way to trigger the function manually, I'm using Vue and I think mailtoui triggers itself at load. Any data that is added afterwards isn't being picked up by mailtoui.

Also, proper npm support would be great, ie being able to `import mailtoui from 'mailtoui';` etc.

Thanks though, this is great!

**Comment by mariordev** [comment]
v0.2.0 provides proper npm support and the ability to run MailtoUI manually. It plays nice with Vue.js. Please see [docs](https://mailtoui.com) for details.
