### ISSUE TITLE
Option to disable the copy button?

### ISSUE THREAD

**Issue by preetibenedict** [mariordev/mailtoui#30]
I am not sure if I am something trivial, but if I have a set of addresses in the mailTo list, the modal's size seems to be increasing to display all the addresses in the copy section. In my case, I have to send emails to quite a few addresses and was wondering if there was someway to disable the copy button (not display it) or not let the modal increase in size.

**Comment by mariordev** [comment]
You could hide the Copy field by adding this to your own CSS:
```
.mailtoui-copy { display:none; visibility:hidden; width:0; height:0; }
```

Hope this helps!

**Comment by preetibenedict** [comment]
Thanks.. That worked
