### ISSUE TITLE
Feat. req. - SVG substitutions

### ISSUE THREAD

**Issue by JayHoltslander** [mariordev/mailtoui#4]
Would be nice if there were a way to swap the SVGs in use for each service that didn't involve modifying the javascript.

As originally submitted [on Twitter](https://twitter.com/j_holtslander/status/1083933561860743169)

**Comment by mariordev** [comment]
This issue has been resolved in v1.0.0.

**Comment by JayHoltslander** [comment]
@mariordev Comments in the file at ``https://cdn.jsdelivr.net/npm/mailtoui@1.0.0/dist/mailtoui-min.js`` say it's version 0.2.2(?)

**Comment by mariordev** [comment]
@JayHoltslander Hi Jay, thanks for bringing this to my attention. A hiccup in the build process did not update the version number in the dist file. It's now fixed in v1.0.1. No code changes.
